I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 193, in script
    bloodiey "Hi!"
Exception: Sayer 'bloodiey' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 193, in script
    bloodiey "Hi!"
  File "C:\Users\blood\renpy\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\blood\renpy\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'bloodiey' is not defined.

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.3.23091805
Bloodiey's meeting 0.0.3
Mon Dec  4 16:23:49 2023
